# -*- coding: utf-8 -*-

varinfo = {
        'pr':  {'coef': 86400., 'units': r'mm day$^{-1}$', 'name': 'Precipitation'},
        'ts':  {'coef': 1.,     'units': r'K',             'name': 'Surface Temperature'},
        'tas': {'coef': 1.,     'units': r'K',             'name': '2-m Temperature'},
        'clt': {'coef': 1.,     'units': r'%',             'name': 'Total Cloud Fraction'},
        'prw': {'coef': 1.,     'units': r'kg m$^{-2}$',   'name': 'Precipitable Water'},
        'rlut':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'TOA Outgoing LW radiation'},
        'rsut':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'TOA Outgoing SW radiation'},
        'hfls':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Surface Latent Heat Flux'},
        'hfss':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Surface Sensible Heat Flux'},
        'ta':  {'coef': 1.,     'units': r'K',             'name': 'Temperature'},
        'hus': {'coef': 1000.,  'units': r'g kf$^{-1}$',   'name': 'Specific Humidity'},
        'ua':  {'coef': 1.,     'units': r'm s$^{-1}$',    'name': 'Zonal Wind'},
        'va':  {'coef': 1.,     'units': r'm s$^{-1}$',    'name': 'Meridional Wind'},
        'wap': {'coef': 864.,   'units': r'hPa day$^{-1}$','name': 'Pressure Vertical Velocity'},
        'mse': {'coef': 0.001,  'units': r'kJ kg$^{-1}$',  'name': 'Moist Static Energy'},
        'fnet':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Atmospheric Net Flux Divergence'},
        'rsa': {'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Atmospheric SW Radiative Flux Divergence'},
        'rla': {'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Atmospheric LW Radiative Flux Divergence'},
        'rna': {'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Atmospheric Net Radiative Flux Divergence'},
        'hfs': {'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Surface Net Turbulent Heat Flux'},
        'hfls':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Surface Turbulent Latent Heat Flux'},
        'hfss':{'coef': 1.,     'units': r'W m$^{-2}$',    'name': 'Surface Turbulent Sensible Heat Flux'},
        'int_mse_advh':{'coef': -1., 'units': r'W m$^{-2}$',    'name': 'Vertically-Integrated MSE horizontal advection'},
        'int_mse_advw':{'coef': -1., 'units': r'W m$^{-2}$',    'name': 'Vertically-Integrated MSE vertical advection'},
        'res':{'coef': 1.,      'units': r'W m$^{-2}$',    'name': 'Vertically-Integrated MSE residual'},
        }
